export type Block =
  | { t: "h2" | "h3" | "p" | "quote"; v: string }
  | { t: "ul"; v: string[] }
  | { t: "img"; src: string; alt: string }
  | { t: "table"; head: string[]; rows: string[][] };

export type BlogPost = {
  slug: string;
  title: string;
  date: string;
  dateDisplay: string;
  readingTime: string;
  category: string;
  cover: string;
  coverAlt: string;
  excerpt: string;
  blocks: Block[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "left-shoulder-rotator-cuff-tear-icd-10-guide",
    title: "Left Shoulder Rotator Cuff Tear: ICD-10 Guide",
    date: "2026-04-26",
    dateDisplay: "26 Apr 2026",
    readingTime: "5 min read",
    category: "Shoulder",
    cover: "/images/blog-sportsman.webp",
    coverAlt: "Athlete holding his shoulder in pain during training",
    excerpt:
      "The ICD-10 code your doctor uses for a left rotator cuff tear shapes your diagnosis, records and insurance. Here is what each code means — and the treatment paths it opens.",
    blocks: [
      { t: "p", v: "Persistent pain in the left shoulder can make basic daily activities feel incredibly difficult. Patients experiencing a dull ache or severe weakness may be suffering from a damaged shoulder joint. When seeking medical care, accurate documentation is a vital step in the recovery process." },
      { t: "p", v: "The specific left shoulder rotator cuff tear ICD-10 code used by healthcare providers directly impacts diagnosis accuracy, medical records, and insurance billing. The International Classification of Diseases (ICD-10) provides specific codes to categorize these injuries based on their severity and cause. Understanding what these classifications mean can empower patients to make informed decisions about their healthcare." },
      { t: "h2", v: "What Is a Rotator Cuff Tear?" },
      { t: "p", v: "The rotator cuff is a group of four muscles and tendons that surround the shoulder joint. These tissues keep the head of the upper arm bone firmly within the shallow socket of the shoulder. A tear occurs when one or more of these tendons detach entirely or partially from the bone." },
      { t: "p", v: "When a patient suffers a left shoulder rotator cuff tear, they often struggle with lifting, reaching, and overhead movements. A tear can result from a sudden injury or develop gradually over time due to wear and tear." },
      { t: "h2", v: "ICD-10-CM Codes for Left Shoulder Rotator Cuff Tears" },
      { t: "p", v: "Medical professionals use specific ICD-10-CM codes to document the exact nature of a shoulder injury. Side-specific documentation is crucial for accurate medical records and proper treatment planning. For a left-shoulder nontraumatic rotator cuff tear, the category includes specific code options based on the level of detail provided by the physician:" },
      { t: "ul", v: [
        "M75.102 — Unspecified rotator cuff tear or rupture of left shoulder, not specified as traumatic.",
        "M75.112 — Incomplete rotator cuff tear or rupture of left shoulder, not specified as traumatic.",
        "M75.122 — Complete rotator cuff tear or rupture of left shoulder, not specified as traumatic.",
      ] },
      { t: "p", v: "Accurate coding depends entirely on detailed clinical documentation. Physicians must clearly note whether the tear is incomplete, complete, or unspecified. Furthermore, if a sudden accident caused the injury, providers use a different set of trauma codes, such as S46.012 for a traumatic strain or tear of the left shoulder." },
      { t: "h2", v: "Common Causes and Symptoms" },
      { t: "p", v: "Rotator cuff injuries occur for a variety of reasons. Many patients develop degenerative tears due to age-related wear, while others experience sudden tears from falls, lifting accidents, or sports trauma. Patients with this condition typically experience a distinct set of symptoms:" },
      { t: "ul", v: [
        "Persistent left shoulder pain.",
        "Noticeable weakness while lifting the arm.",
        "Pain during overhead movements, such as combing hair or reaching for a shelf.",
        "Night pain, especially when sleeping on the affected side.",
        "A reduced range of motion in the shoulder joint.",
      ] },
      { t: "h2", v: "How a Tear Is Diagnosed" },
      { t: "p", v: "To recommend the most effective care plan, an orthopedic specialist conducts a comprehensive evaluation. This typically includes a physical examination, a review of medical history, and imaging studies such as X-rays, ultrasound, or MRI scans to confirm the tear's size and location." },
      { t: "h2", v: "Expert Treatment Options" },
      { t: "p", v: "Modern orthopedic care offers both non-invasive and surgical approaches to reclaim shoulder mobility." },
      { t: "h3", v: "Non-Surgical Treatment" },
      { t: "p", v: "Many patients find significant relief through conservative, non-invasive options. A tailored rehabilitation program, activity modification, anti-inflammatory medication, and ultrasound-guided injections often reduce pain and restore function without surgery." },
      { t: "h3", v: "Surgical Treatment" },
      { t: "p", v: "When non-invasive methods do not provide adequate relief, or if the tendon is completely detached, arthroscopic repair becomes the recommended path. Minimally invasive techniques allow precise tendon reattachment with smaller incisions, less pain, and faster recovery." },
      { t: "h2", v: "Start Your Recovery Journey Today" },
      { t: "p", v: "Accurate diagnosis and precise medical coding are the foundational steps toward effective treatment. If you are experiencing persistent shoulder pain, consult a specialist to receive a thorough evaluation and a personalised treatment plan." },
    ],
  },
  {
    slug: "shoulder-rotator-cuff-tear-symptoms-causes-treatments",
    title: "Shoulder Rotator Cuff Tear: Symptoms, Causes, and Treatments",
    date: "2026-04-11",
    dateDisplay: "11 Apr 2026",
    readingTime: "7 min read",
    category: "Rotator Cuff",
    cover: "/images/blog-physio.webp",
    coverAlt: "Physiotherapist checking a patient's shoulder flexibility",
    excerpt:
      "From the first pinch to full-thickness tears — understand what causes rotator cuff injuries, how they are diagnosed, and every treatment option from therapy to keyhole repair.",
    blocks: [
      { t: "p", v: "A shoulder rotator cuff tear is a common orthopedic injury that can significantly restrict movement and cause persistent discomfort. Active individuals often experience this condition, leading to noticeable shoulder pain and weakness that disrupts daily activities." },
      { t: "p", v: "Early diagnosis and timely intervention are crucial for a successful recovery and restoring full mobility. Patients who seek prompt medical attention often experience better outcomes — and a quicker return to the activities they love." },
      { t: "h2", v: "What Is the Rotator Cuff?" },
      { t: "p", v: "The rotator cuff is a specialized group of four muscles and their connecting tendons that surround the shoulder joint. This structural network plays a vital role in everyday movement. It actively stabilizes the shoulder joint, helps lift the arm, and assists with seamless shoulder rotation." },
      { t: "h2", v: "What Is a Shoulder Rotator Cuff Tear?" },
      { t: "p", v: "A tear occurs when one or more of these tendons detach completely or partially from the head of the humerus (upper arm bone). Medical professionals categorize these injuries into two main types:" },
      { t: "ul", v: [
        "Partial rotator cuff tear — the tendon is damaged but not completely severed.",
        "Full thickness rotator cuff tear — the soft tissue is split completely, often detaching the tendon entirely from the bone.",
      ] },
      { t: "p", v: "These tears can develop gradually due to aging or happen suddenly following a specific injury." },
      { t: "h2", v: "Causes of a Shoulder Rotator Cuff Tear" },
      { t: "h3", v: "Degenerative Causes" },
      { t: "p", v: "Many tears result from a natural wearing down of the tendon. Age-related wear and tear is the most common factor. Repeated stress on the shoulder over time weakens the tissue. Additionally, a reduced blood supply to the tendons as people age limits the body's natural ability to repair minor tendon damage." },
      { t: "h3", v: "Traumatic Causes" },
      { t: "p", v: "Sudden injuries can also damage the shoulder. A fall on an outstretched hand, lifting something heavy suddenly, a high-impact sports injury, or a direct blow to the shoulder can cause an immediate tear." },
      { t: "h2", v: "Risk Factors" },
      { t: "p", v: "Several factors increase the likelihood of sustaining this injury. Individuals over the age of 40 face a higher risk due to tissue degeneration. Repetitive overhead work and playing sports like tennis, cricket, baseball, or swimming place constant stress on the joint. Poor shoulder mechanics, a previous shoulder injury, smoking, and poor tissue healing also elevate the risk." },
      { t: "h2", v: "Symptoms of Shoulder Rotator Cuff Tear" },
      { t: "p", v: "Recognizing rotator cuff tear symptoms early allows for faster intervention. Patients frequently report pain when lifting or lowering the arm, weakness in the shoulder, crackling sensations during movement, and difficulty performing routine tasks that require reaching overhead or behind the back." },
      { t: "h2", v: "When to See a Doctor" },
      { t: "p", v: "Medical attention is necessary if shoulder pain lasts for more than a few weeks. Patients should consult a specialist immediately following an acute injury — especially when accompanied by a popping sensation, immediate weakness, or an inability to move the arm." },
      { t: "h2", v: "How Is a Rotator Cuff Tear Diagnosed?" },
      { t: "h3", v: "Medical History" },
      { t: "p", v: "A physician begins by discussing the nature of the pain. They will ask about previous injuries, repetitive activities, occupation, and the specific movements that trigger discomfort." },
      { t: "h3", v: "Physical Examination" },
      { t: "p", v: "The doctor will perform range of motion testing to see how well the arm moves. Strength testing and special orthopedic maneuvers — such as the painful arc test — help identify which tendon is involved and the severity of the damage." },
      { t: "h3", v: "Imaging Tests" },
      { t: "p", v: "An X-ray helps rule out bone problems like arthritis or bone spurs. An ultrasound assesses soft tissue in real time, while an MRI provides detailed images of the tendons, revealing partial and complete tears with high accuracy." },
      { t: "h2", v: "Treatment Options" },
      { t: "h3", v: "Non-Surgical Treatment" },
      { t: "p", v: "Effective shoulder pain treatment often begins with conservative methods. Rest and activity modification reduce strain on the joint. A structured physical therapy program strengthens the surrounding muscles. Nonsteroidal anti-inflammatory drugs manage pain and swelling, while corticosteroid injections offer relief for persistent inflammation." },
      { t: "h3", v: "Surgical Treatment" },
      { t: "p", v: "When non-surgical rotator cuff tear treatment fails or the tear is severe, surgery becomes necessary. Arthroscopic tendon repair uses small incisions and a camera to reattach the torn tendon to the bone. Open repair may be recommended for massive tears. Most procedures are performed on an outpatient basis, allowing patients to return home the same day." },
      { t: "h2", v: "Recovery After Treatment" },
      { t: "p", v: "Successful rotator cuff injury recovery depends heavily on the tear size and the specific treatment received. Initial healing focuses on pain management and passive movement. Progressive physical therapy then restores strength and flexibility. Complete recovery may take several months, but following the rehabilitation plan closely delivers the best long-term outcomes." },
      { t: "h2", v: "What Happens If a Tear Is Left Untreated?" },
      { t: "p", v: "Ignoring a tear leads to worsening conditions. Patients face persistent pain and increasing weakness. Over time, the tear can enlarge, the muscle may atrophy, and shoulder arthritis can develop. Early treatment prevents these complications and protects long-term joint function." },
      { t: "h2", v: "Tips to Prevent Rotator Cuff Injuries" },
      { t: "p", v: "Proactive habits keep the shoulder joint healthy. Always warm up thoroughly before participating in sports. Strengthen the rotator cuff muscles with targeted resistance exercises. Practice proper lifting techniques, take regular breaks during repetitive tasks, and maintain good posture to reduce unnecessary strain." },
      { t: "h2", v: "Take Action for a Pain-Free Shoulder" },
      { t: "p", v: "Early diagnosis and consistent care significantly improve patient outcomes. Understanding the symptoms, causes, and available treatments for rotator cuff tears empowers patients to seek timely help. Experiencing shoulder pain or weakness? Consult a shoulder specialist for an accurate diagnosis and an effective treatment plan." },
    ],
  },
  {
    slug: "finding-the-right-shoulder-specialist",
    title: "Finding the Right Shoulder Specialist for Your Recovery",
    date: "2026-04-11",
    dateDisplay: "11 Apr 2026",
    readingTime: "6 min read",
    category: "Guide",
    cover: "/images/blog-examining.webp",
    coverAlt: "Doctor examining a patient's shoulder",
    excerpt:
      "Board certification, fellowship training, procedure volume — the credentials and questions that separate a true shoulder specialist from a generalist, and how to verify them.",
    blocks: [
      { t: "p", v: "Shoulder pain stemming from rotator cuff tears, instability, arthritis, frozen shoulder, sports injuries, or overuse conditions can severely impact daily life. Reclaiming mobility starts with identifying the right medical professional. A qualified doctor must possess strong clinical credentials alongside demonstrated experience treating specific shoulder problems." },
      { t: "h2", v: "What Is a Shoulder Specialist?" },
      { t: "p", v: "A shoulder specialist is a doctor highly focused on diagnosing and treating conditions of the shoulder. Most of these professionals are orthopaedic surgeons who have completed additional, highly specialized training in shoulder and elbow care or orthopaedic sports medicine following their standard residency." },
      { t: "h2", v: "Board Certification Is Essential" },
      { t: "p", v: "Board certification should be one of the first credentials verified. This status reflects rigorous testing, adherence to strict medical standards, and an ongoing commitment to professional maintenance. Patients should ensure their doctor is either board-certified or board-eligible in orthopaedic surgery." },
      { t: "h2", v: "The Value of Fellowship Training" },
      { t: "p", v: "Fellowship training provides doctors with advanced, sub-specialized education. A fellowship in shoulder and elbow surgery or sports medicine equips a specialist to handle highly complex cases. This added expertise is crucial for treating massive tears and joint instability, as well as for performing arthroscopy and total shoulder replacement surgery." },
      { t: "h2", v: "Look for Condition-Specific Experience" },
      { t: "p", v: "Condition-specific experience matters just as much as general medical credentials. Patients should ask whether the doctor regularly treats their exact issue. Look for a specialist with extensive experience managing:" },
      { t: "ul", v: [
        "Rotator cuff tears",
        "Shoulder dislocation or instability",
        "Labral injuries",
        "Frozen shoulder",
        "Arthritis",
        "Shoulder replacement",
      ] },
      { t: "h2", v: "Ask About Procedure Volume and Surgical Experience" },
      { t: "p", v: "If surgery is a consideration, patients must inquire about the specialist's procedure volume. Asking how often the doctor performs a recommended surgery each year helps gauge their technical proficiency. It is also wise to ask about their expected patient outcomes and historical complication rates." },
      { t: "h2", v: "Clear Diagnosis and Treatment Options" },
      { t: "p", v: "A reputable shoulder specialist conducts a careful evaluation and clearly explains what is causing the joint pain. They prioritize non-invasive options first, discussing physical therapy, medication, and injections before recommending surgery. Every recommendation should come with a clear explanation of risks and benefits." },
      { t: "h2", v: "Hospital or Surgery Center Quality Also Matters" },
      { t: "p", v: "The location where the doctor operates directly impacts recovery and results. Patients should evaluate the hospital's reputation, the availability of advanced imaging technology, infection rates, and the quality of the supporting staff and rehabilitation services." },
      { t: "h2", v: "Check for Professional Memberships" },
      { t: "p", v: "Active participation in professional organizations, such as holding the FAAOS credential (Fellow of the American Academy of Orthopaedic Surgeons), signals a commitment to continued education and adherence to the highest standards of orthopedic care." },
      { t: "h2", v: "Rehabilitation Planning Is Part of the Qualification" },
      { t: "p", v: "Expert care does not end in the operating room. A strong specialist provides a comprehensive rehabilitation plan, works closely with physical therapists, and schedules regular follow-up appointments to monitor progress and adjust treatment." },
      { t: "h2", v: "Questions to Ask Before Choosing" },
      { t: "ul", v: [
        "Are you board-certified or board-eligible in orthopaedic surgery?",
        "Have you completed fellowship training in shoulder surgery?",
        "How many procedures like mine do you perform each year?",
        "What are your typical outcomes and complication rates?",
        "What non-surgical options do you recommend trying first?",
      ] },
      { t: "h2", v: "Red Flags to Watch Out For" },
      { t: "p", v: "Be cautious if a doctor provides vague answers about their credentials or fails to explain a diagnosis clearly. Pressure to schedule immediate surgery without exploring conservative treatments, or a lack of written treatment plans, are warning signs that warrant a second opinion." },
      { t: "h2", v: "Start Your Recovery Journey Today" },
      { t: "p", v: "Finding the right shoulder specialist involves looking beyond a medical title. Patients must verify credentials, evaluate experience, and choose a doctor who communicates clearly. Taking these steps leads to better surgical outcomes, smoother rehabilitation, and restored quality of life." },
    ],
  },
  {
    slug: "non-surgical-treatments-for-shoulder-pain",
    title: "Non-Surgical Treatments for Shoulder Pain: The Specialist's Approach",
    date: "2026-02-19",
    dateDisplay: "19 Feb 2026",
    readingTime: "7 min read",
    category: "Treatment",
    cover: "/images/blog-anatomy.webp",
    coverAlt: "3D anatomical visualization of the shoulder joint skeletal structure",
    excerpt:
      "Surgery is the last resort, not the first step. From ultrasound-guided injections to PRP therapy — the complete non-surgical toolkit for shoulder pain at Aswini Hospital.",
    blocks: [
      { t: "p", v: "Living with shoulder pain changes the way you move through the world. Simple tasks like reaching for a coffee mug, combing your hair, or finding a comfortable sleeping position become daily battles." },
      { t: "p", v: "For many patients, the fear of seeing a shoulder pain specialist is tied directly to the fear of surgery. There is a common misconception that walking into an orthopedic office automatically leads to the operating room. However, at Aswini Hospital Ltd., Thrissur, our philosophy is grounded in functional recovery through conservative care first. Surgery is a powerful tool, but for many conditions, it is the last resort — not the first step." },
      { t: "h2", v: "When Is It an Emergency? Red Flags to Watch For" },
      { t: "p", v: "While most shoulder pain can be managed with scheduled care, certain symptoms require immediate medical attention. Do not delay consultation if you experience:" },
      { t: "ul", v: [
        "Visible deformity — a “stepped” appearance of the shoulder or collarbone.",
        "Loss of function — total inability to lift the arm.",
        "Neurological symptoms — numbness, tingling, or a “cold” feeling in the hand or arm.",
        "Associated chest pain — sudden, intense shoulder pain accompanied by chest pressure or shortness of breath (this may indicate a cardiac event).",
      ] },
      { t: "h2", v: "Precision Diagnosis: The Foundation of Non-Surgical Success" },
      { t: "p", v: "Effective treatment begins with an accurate diagnosis. Beyond standard X-rays, our specialists use advanced diagnostic tools to truly “see” the source of your pain." },
      { t: "p", v: "We utilize high-resolution MRI and Musculoskeletal Ultrasound (MSK) to identify micro-tears, inflammation, and soft tissue issues that general exams might miss. Furthermore, clinical “stress tests” allow us to manually evaluate the stability of the rotator cuff and labrum, ensuring we understand the mechanical root of your discomfort before prescribing a treatment plan." },
      { t: "h2", v: "Common Conditions We Treat Without Surgery" },
      { t: "p", v: "Many painful shoulder conditions respond exceptionally well to non-invasive therapies." },
      { t: "h3", v: "Rotator Cuff Tendinitis & Impingement" },
      { t: "p", v: "This condition often feels like a pinch when lifting the arm. We focus on biomechanical correction to reduce irritation on the tendons, allowing them to heal naturally." },
      { t: "h3", v: "Frozen Shoulder (Adhesive Capsulitis)" },
      { t: "p", v: "Stiffness and pain characterize this condition. We utilize specialized stretching protocols or hydrodilatation — a procedure to gently expand the joint capsule — to “thaw” the shoulder and restore range of motion." },
      { t: "h3", v: "Calcific Tendonitis" },
      { t: "p", v: "Calcium deposits can form on tendons, causing significant pain. Advanced non-surgical techniques can break down these deposits and promote healing." },
      { t: "h3", v: "Bursitis" },
      { t: "p", v: "When the fluid-filled sacs (bursae) that cushion the joint become inflamed, we focus on draining or reducing the inflammation to restore smooth, painless movement." },
      { t: "h2", v: "The Non-Surgical Toolkit at Aswini Hospital" },
      { t: "h3", v: "1. Integrated Physical Rehabilitation" },
      { t: "p", v: "Our surgeons design customized protocols that are executed by our in-house physiotherapists. The focus is on restoring strength, range of motion, and correct movement patterns — the true foundation of recovery." },
      { t: "h3", v: "2. Ultrasound-Guided Injections" },
      { t: "p", v: "For immediate relief and inflammation control, we offer precise injections delivered exactly where they are needed:" },
      { t: "ul", v: [
        "Corticosteroids — delivered directly to the site of inflammation.",
        "Viscosupplementation (Hyaluronic Acid) — acts as a lubricant for the joint, particularly helpful for early arthritis.",
      ] },
      { t: "h3", v: "3. Regenerative Orthobiologics (PRP Therapy)" },
      { t: "p", v: "Platelet-Rich Plasma (PRP) therapy uses your own blood platelets to accelerate natural healing, particularly effective for partial tendon tears and early cartilage degeneration." },
      { t: "h3", v: "4. Advanced Modalities" },
      { t: "p", v: "We employ technologies such as shockwave therapy, TENS, and therapeutic ultrasound to stimulate blood flow, reduce pain, and promote tissue repair." },
      { t: "h2", v: "The Sleep & Lifestyle Recovery Plan" },
      { t: "p", v: "Recovery doesn't stop when you leave the clinic. We help you adjust your daily life to support healing:" },
      { t: "ul", v: [
        "Ergonomics — adjusting desk heights and monitor positions to reduce strain.",
        "Shoulder-safe sleep — using pillows to support the joint and avoiding “side-sleeper” impingement positions.",
        "Activity modification — learning how to stay active and maintain fitness without aggravating the injury.",
      ] },
      { t: "img", src: "/images/blog-consult.webp", alt: "Dr. Dhanil Charly, consultant orthopaedic surgeon, in consultation" },
      { t: "h2", v: "Why Choose Aswini Hospital Ltd., Thrissur?" },
      { t: "p", v: "At Aswini Hospital, we offer a continuum of care where surgeons and therapists work under one roof, ensuring seamless communication and a unified recovery plan. Most shoulder pain can be resolved through a disciplined, specialist-led non-surgical plan — and early intervention delivers the best results." },
      { t: "p", v: "Book a consultation with Dr. Dhanil Charly at Aswini Hospital Ltd., Thrissur — call or WhatsApp +91 80788 90229." },
    ],
  },
  {
    slug: "shoulder-pain-specialist-or-general-doctor",
    title: "Shoulder Pain: Do You Need a Specialist or a General Doctor?",
    date: "2026-02-18",
    dateDisplay: "18 Feb 2026",
    readingTime: "6 min read",
    category: "Guide",
    cover: "/images/blog-gym.webp",
    coverAlt: "Man training with gym equipment",
    excerpt:
      "Up to 25% of adults live with shoulder pain. The first doctor you call decides how fast — and how much it costs — to fix it. A clear roadmap for choosing right.",
    blocks: [
      { t: "p", v: "Shoulder pain is incredibly common. In fact, studies suggest it affects up to 25% of adults at any given time. Whether it's a nagging ache after a workout or a sharp pain that keeps you up at night, the first question is often the hardest: “Who should I call?”" },
      { t: "p", v: "Choosing the right doctor isn't just about convenience. The first clinical stop you make often determines the speed of your recovery and the cost of your care. My goal is to give you a clear roadmap to help you distinguish between broad orthopedic care and sub-specialized expertise." },
      { t: "quote", v: "Safety note: if you have sudden shoulder deformity, loss of a pulse in your arm (it feels cold or pale), or shoulder pain accompanied by chest pressure or shortness of breath — skip the appointment and head to the ER immediately." },
      { t: "h2", v: "The General Orthopedic Doctor: The “All-In-One” Expert" },
      { t: "p", v: "Think of a general orthopedic doctor as the primary care physician of the musculoskeletal system. These are board-certified surgeons trained to treat bones, joints, ligaments, and tendons from your neck down to your toes." },
      { t: "p", v: "Ideal scenarios for a generalist:" },
      { t: "ul", v: [
        "Acute, first-time injuries — simple trips, falls, or minor sprains.",
        "Standard fractures — “simple” breaks that don't shatter the joint surface.",
        "Multiple pains — if you're dealing with both a sore shoulder and a bad knee, a generalist can look at the systemic picture (like inflammatory arthritis).",
      ] },
      { t: "p", v: "The biggest benefit here is usually availability. You can often get an appointment faster, which is crucial for acute, simple injuries." },
      { t: "h2", v: "The Shoulder Specialist: The Sub-Specialty Expert" },
      { t: "p", v: "A shoulder specialist is an orthopedic surgeon who has gone a step further. Beyond their residency, I have completed a Fellowship specifically in Shoulder and Elbow surgery. This additional year of intensive training focuses solely on the complex mechanics of the upper extremity." },
      { t: "p", v: "Volume matters in surgery. While a generalist might see a variety of cases, a specialist often performs hundreds of the same specific procedure — like keyhole surgery (arthroscopy) for rotator cuff repairs — every single year." },
      { t: "p", v: "Complex conditions we treat:" },
      { t: "ul", v: [
        "Failed previous surgeries — revision work to fix repairs that didn't hold.",
        "Chronic instability — shoulders that recurrently dislocate.",
        "Advanced degeneration — complex replacements, such as reverse shoulder arthroplasty.",
        "Complex tears — massive rotator cuff tears and labral lesions.",
      ] },
      { t: "h2", v: "Specialist vs. Generalist: A Side-by-Side Comparison" },
      { t: "table", head: ["Feature", "General Orthopedist", "Shoulder Specialist"], rows: [
        ["Training", "5-Year Residency", "Residency + 1-Year Fellowship"],
        ["Focus", "Whole Body / General Trauma", "Shoulder & Elbow Only"],
        ["Surgical Tech", "Standard Arthroscopy", "Advanced/Revision Reconstruction"],
        ["Best For", "Initial Diagnosis & Simple Fixes", "Chronic, Severe, or Failed Cases"],
      ] },
      { t: "h2", v: "5 Signs You Specifically Need a Shoulder Specialist" },
      { t: "ul", v: [
        "Mechanical locking — your shoulder feels “stuck,” catches, or clicks painfully during movement. This often indicates a labral tear or loose body.",
        "Recurrent instability — your shoulder has dislocated more than once, or feels like it might “slip out” during activity.",
        "Night pain that wakes you — persistent pain when lying on the side can signal a rotator cuff tear.",
        "Failed previous treatment — pain that persisted after physiotherapy or an earlier surgery needs sub-specialist review.",
        "Overhead athlete or manual worker — repetitive overhead demand deserves specialist-level care planning.",
      ] },
      { t: "h2", v: "Diagnostic Precision: Why It Matters" },
      { t: "p", v: "One of the biggest advantages of seeing a specialist is diagnostic nuance. We look at MRI scans differently because we see the same patterns hundreds of times a year. What looks like a simple “tendinitis” on a report can be a hidden partial-thickness tear that needs a completely different treatment path." },
      { t: "h2", v: "Putting Your Recovery First" },
      { t: "p", v: "Both generalists and specialists play vital roles in orthopedic care, but the complexity of your injury should guide your choice. If you are struggling with persistent shoulder pain, consult a board-certified professional to get an accurate diagnosis and the right plan — the first time." },
      { t: "p", v: "Call or WhatsApp +91 80788 90229 to book a consultation." },
    ],
  },
  {
    slug: "common-gym-mistakes-that-injure-shoulders",
    title: "STOP Making These 3 Common Gym Mistakes That Injure Shoulders",
    date: "2025-08-26",
    dateDisplay: "26 Aug 2025",
    readingTime: "5 min read",
    category: "Prevention",
    cover: "/images/blog-gym.webp",
    coverAlt: "Man doing biceps training at the gym",
    excerpt:
      "Your shoulder is built for movement, not abuse. A shoulder surgeon's guide to the three most common gym mistakes that end in my clinic — and exactly what to do instead.",
    blocks: [
      { t: "p", v: "If you're someone who loves to work out, lift weights, or stay fit — great! But as a shoulder specialist, I see a lot of injuries caused by common gym mistakes that are totally avoidable." },
      { t: "p", v: "Your shoulder is one of the most mobile — but also most unstable — joints in the body. It's built for movement, not abuse. Let me walk you through the top 3 mistakes I see at the gym that end up bringing people to my clinic with pain, weakness, or even rotator cuff tears." },
      { t: "h2", v: "Mistake #1: Lifting Heavy Weights Without Warming Up" },
      { t: "p", v: "Jumping straight into a bench press or overhead dumbbell press without warming up is one of the fastest ways to injure your shoulder." },
      { t: "p", v: "Why it's harmful:" },
      { t: "ul", v: [
        "Cold muscles are stiff and prone to tears",
        "Your rotator cuff isn't activated",
        "Poor blood flow increases injury risk",
      ] },
      { t: "p", v: "What to do instead:" },
      { t: "ul", v: [
        "Spend 5–10 minutes warming up",
        "Do dynamic stretches like arm circles, shoulder rolls, and resistance band work",
        "Start your first set with lighter weights",
      ] },
      { t: "quote", v: "Shoulder tip: always “activate before you elevate.”" },
      { t: "h2", v: "Mistake #2: Incorrect Form in Overhead Exercises" },
      { t: "p", v: "Exercises like shoulder press, snatch, or lat pulldown behind the neck can hurt you more than help — if your form is wrong." },
      { t: "p", v: "Common issues:" },
      { t: "ul", v: [
        "Arching your back while pressing overhead",
        "Pulling the bar too far behind your neck",
        "Not engaging your core or scapular stabilizers",
      ] },
      { t: "p", v: "Do this instead:" },
      { t: "ul", v: [
        "Keep a neutral spine",
        "Perform lat pulldowns in front of your head",
        "Use mirrors or a trainer to check your form",
      ] },
      { t: "p", v: "Research shows poor form is a major contributor to impingement syndrome and rotator cuff tendinitis in gym-goers." },
      { t: "h2", v: "Mistake #3: Training Chest & Arms, Ignoring Back & Rotator Cuff" },
      { t: "p", v: "Everyone loves training chest and biceps. But if you ignore the small stabilizing muscles of the shoulder, you create muscle imbalances that pull the joint out of alignment." },
      { t: "p", v: "What happens:" },
      { t: "ul", v: [
        "Strong front muscles, weak back muscles",
        "Poor posture and scapular control",
        "Increased risk of tendon tears and impingement",
      ] },
      { t: "p", v: "The fix:" },
      { t: "ul", v: [
        "Include rotator cuff exercises like external rotations and scapular retractions",
        "Strengthen posterior deltoid, rhomboids, and lower traps",
        "Add “prehab” work at the start of your workout — not the end",
      ] },
      { t: "quote", v: "Surgeon's note: the best athletes have strong stabilizers, not just big muscles." },
      { t: "h2", v: "Symptoms You Shouldn't Ignore" },
      { t: "p", v: "If you feel any of the following after a workout, get your shoulder evaluated:" },
      { t: "ul", v: [
        "Sharp pain while lifting your arm",
        "Pain at night, especially lying on that side",
        "Weakness lifting overhead",
        "Clicking or catching sensations",
      ] },
      { t: "h2", v: "When to See a Shoulder Specialist" },
      { t: "p", v: "If your shoulder pain lasts more than a few days or keeps coming back, it's time for a proper evaluation. Early treatment prevents small tears from becoming big ones." },
      { t: "p", v: "Don't wait until the pain becomes permanent. Call or WhatsApp +91 80788 90229." },
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export const latestPosts = (n: number): BlogPost[] =>
  [...blogPosts].sort((a, b) => (a.date < b.date ? 1 : -1)).slice(0, n);
